kind: pipeline
name: default

steps:
- name: ping
  image: mongo:4
  commands:
  - sleep 60
  - mongo --host mongo --eval "db.version()"
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go  
  commands:
  - sleep 60
  - go test

services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017