kind: pipeline
name: default

steps:
- name: ping
  image: mongo:4
  commands:
  - sleep 60
  - mongo --host mongo --eval "db.version()"

- name: test
  image: golang:latest
  environment:
    MONGODB_URI: mongodb://mongo:27017
  commands:
  - go test -race -cover -coverprofile=coverage.txt -covermode=atomic -coverpkg $(go list github.com/go-stuff/mongostore/...) github.com/go-stuff/mongostore/...

- name: coverage
  image: plugins/codecov
  settings: 
    token:
      from_secret: CODECOV_TOKEN
    files:
    - coverage.txt

services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017